export const budgets = [
    {
        id: 0,
        name: "Budżet Luty 2018",
        categories: [
            { id: 0, name: "Sport", declaredAmount: 200, enteredAmount: 1000},
            { id: 1, name: "Transport", declaredAmount: 600, enteredAmount: 600},
            { id: 2, name: "Pożywienie i napoje", declaredAmount: 600, enteredAmount: 800},
            { id: 3, name: "Rozrywka", declaredAmount: 100, enteredAmount: 50},
            { id: 4, name: "Dom", declaredAmount: 1000, enteredAmount: 800},
            { id: 5, name: "Nauka", declaredAmount: 300, enteredAmount: 300},
        ],
        startDate: "2018-02-01",
        endDate: "2018-02-28",
        isAlive: true,
        // timeToEnd: 999,
    },
    {
        id: 1,
        name: "Budżet Marzec 2018",
        categories: [
            { id: 0, name: "Sport", declaredAmount: 200, enteredAmount: 0},
            { id: 1, name: "Transport", declaredAmount: 600, enteredAmount: 0},
            { id: 2, name: "Pożywienie i napoje", declaredAmount: 600, enteredAmount: 0},
            { id: 3, name: "Rozrywka", declaredAmount: 100, enteredAmount: 0},
            { id: 4, name: "Dom", declaredAmount: 1000, enteredAmount: 0},
            { id: 5, name: "Nauka", declaredAmount: 300, enteredAmount: 0},
        ],
        startDate: "2018-03-01",
        endDate: "2018-03-31",
        isAlive: true,
        // timeToEnd: 999,
    },
    {
        id: 2,
        name: "Budżet 2018",
        categories: [
            { id: 0, name: "Sport", declaredAmount: 10000, enteredAmount: 0},
            { id: 1, name: "Transport", declaredAmount: 20000, enteredAmount: 0},
            { id: 2, name: "Pożywienie i napoje", declaredAmount: 30000, enteredAmount: 0},
            { id: 3, name: "Rozrywka", declaredAmount: 1000, enteredAmount: 0},
            { id: 4, name: "Dom", declaredAmount: 20000, enteredAmount: 0},
            { id: 5, name: "Nauka", declaredAmount: 40000, enteredAmount: 0},
        ],
        startDate: "2018-01-01",
        endDate: "2018-12-31",
        isAlive: true,
        // timeToEnd: 999,
    },
]
